version: 2.1

executors:
  macos:
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    macos:
      xcode: << parameters.version >>
    parameters:
      version:
        description: "Xcode version"
        default: "10.2.1"
        type: string

jobs:
  audit:
    executor: macos
    parameters:
      version:
        description: "Xcode version"
        default: "10.2.1"
        type: string
    steps:
      - checkout
      - restore_cache:
          key: homebrew-floss-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Lint formulae
          command: |
            for formula in ./*.rb
            do
              brew audit --strict $formula
            done
      - save_cache:
          key: homebrew-floss-{{ checksum ".circleci/config.yml" }}
          paths:
            - /usr/local/Homebrew/Library/Homebrew/vendor/bundle
  install:
    executor: macos
    parameters:
      version:
        description: "Xcode version"
        default: "10.2.1"
        type: string
    steps:
      - checkout
      - run:
          name: Test installing formulae
          command: |
            for formula in ./*.rb
            do
              brew install --display-times --verbose $formula
            done

workflows:
  ci:
    jobs:
      - install:
          name: "macos-high-sierra"
          version: "10.2.3"
      - install:
          name: "macos-mojave"
          version: "10.3.0"
