version: 2.1

executors:
  macos:
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    macos:
      xcode: << parameters.xcode-version >>
    parameters:
      xcode-version:
        description: Determines the version of MacOS that will be used for a job.
        type: enum
        enum:
          # See https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
          - "10.1.0" # MacOS “High Sierra” 10.13.6
          - "11.1.0" # MacOS “Mojave” 10.14.4
          - "11.3.0" # MacOS “Catalina” 10.15.1

jobs:
  audit:
    executor: << parameters.e >>
    parameters:
      e:
        type: executor
    steps:
      - checkout
      - restore_cache:
          key: homebrew-floss-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Audit formulae
          command: |
            for formula in ./*.rb
            do
              brew audit --strict $formula
            done
      - save_cache:
          key: homebrew-floss-{{ checksum ".circleci/config.yml" }}
          paths:
            - /usr/local/Homebrew/Library/Homebrew/vendor/bundle

  test:
    executor: << parameters.e >>
    parameters:
      e:
        type: executor
    steps:
      - checkout
      - run:
          name: Test formulae
          command: |
            git -C "$(brew --repo homebrew/core)" fetch --unshallow
            for formula in ./*.rb
            do
              brew install --display-times --verbose $formula
              brew test --verbose $formula
            done

workflows:
  Test:
    jobs:
      - test:
          name: Test (MacOS High Sierra)
          e:
            name: macos
            xcode-version: "10.1.0"
      - test:
          name: Test (MacOS Mojave)
          e:
            name: macos
            xcode-version: "11.1.0"
      - test:
          name: Test (MacOS Catalina)
          e:
            name: macos
            xcode-version: "11.3.0"

  # This workflow is commented out because these jobs will fail until the problem described here:
  # https://github.com/FundingCircle/homebrew-floss/issues/9 is fixed.
  # Audit:
  #   jobs:
  #     - audit:
  #        name: Audit (MacOS High Sierra)
  #        xcode-version: "10.2.3"
  #     - audit:
  #        name: Audit (MacOS Mojave)
  #        xcode-version: "10.3.0"
  #     - audit:
  #        name: Audit (MacOS Catalina)
  #        xcode-version: "11.3.0"
