version: 2
jobs:
  build:
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Test installing formulae
          command: |
            for formula in ./*.rb
            do
              brew install --display-times --verbose $formula
            done
